
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xb2\xf2\x8a\xfe&2\xb0dY\xfa\xda\xcbT\xbe\xbaz'
    
_lr_action_items = {'$end':([2,3,5,7,8,10,19,21,23,24,25,26,27,29,30,],[-13,-11,0,-12,-2,-13,-9,-1,-10,-3,-6,-4,-5,-8,-7,]),'FRAC':([0,1,6,9,12,13,15,16,17,18,20,],[1,1,1,1,1,1,1,1,1,1,1,]),'NAME':([0,1,6,9,12,13,15,16,17,18,20,],[2,10,10,10,10,10,10,10,10,10,10,]),'TIMES':([2,3,7,8,10,11,14,19,21,22,23,24,25,26,27,28,29,30,],[-13,-11,-12,18,-13,18,18,-9,18,18,-10,18,-6,18,-5,18,-8,-7,]),'END':([3,7,10,19,23,24,25,26,27,28,29,30,],[-11,-12,-13,-9,-10,-3,-6,-4,-5,30,-8,-7,]),'NUMBER':([0,1,6,9,12,13,15,16,17,18,20,],[3,3,3,3,3,3,3,3,3,3,3,]),'MINUS':([0,1,2,3,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,],[9,9,-13,-11,9,-12,17,9,-13,17,9,9,17,9,9,9,9,-9,9,17,17,-10,-3,-6,-4,-5,17,-8,-7,]),'MIDDLE':([3,7,10,11,19,23,24,25,26,27,29,30,],[-11,-12,-13,20,-9,-10,-3,-6,-4,-5,-8,-7,]),'EQUALS':([2,],[12,]),'PLUS':([2,3,7,8,10,11,14,19,21,22,23,24,25,26,27,28,29,30,],[-13,-11,-12,15,-13,15,15,-9,15,15,-10,-3,-6,-4,-5,15,-8,-7,]),'LPAREN':([0,1,4,6,9,12,13,15,16,17,18,20,],[6,6,13,6,6,6,6,6,6,6,6,6,]),'RPAREN':([3,7,10,14,19,22,23,24,25,26,27,29,30,],[-11,-12,-13,23,-9,29,-10,-3,-6,-4,-5,-8,-7,]),'PI':([0,1,6,9,12,13,15,16,17,18,20,],[7,7,7,7,7,7,7,7,7,7,7,]),'SIN':([0,1,6,9,12,13,15,16,17,18,20,],[4,4,4,4,4,4,4,4,4,4,4,]),'DIVIDE':([2,3,7,8,10,11,14,19,21,22,23,24,25,26,27,28,29,30,],[-13,-11,-12,16,-13,16,16,-9,16,16,-10,16,-6,16,-5,16,-8,-7,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,1,6,9,12,13,15,16,17,18,20,],[8,11,14,19,21,22,24,25,26,27,28,]),'statement':([0,],[5,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> NAME EQUALS expression','statement',3,'p_statement_assign','/home/kristoffer/PycharmProjects/test/calc.py',69),
  ('statement -> expression','statement',1,'p_statement_expr','/home/kristoffer/PycharmProjects/test/calc.py',73),
  ('expression -> expression PLUS expression','expression',3,'p_expression_binop','/home/kristoffer/PycharmProjects/test/calc.py',77),
  ('expression -> expression MINUS expression','expression',3,'p_expression_binop','/home/kristoffer/PycharmProjects/test/calc.py',78),
  ('expression -> expression TIMES expression','expression',3,'p_expression_binop','/home/kristoffer/PycharmProjects/test/calc.py',79),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression_binop','/home/kristoffer/PycharmProjects/test/calc.py',80),
  ('expression -> FRAC expression MIDDLE expression END','expression',5,'p_expression_devide','/home/kristoffer/PycharmProjects/test/calc.py',87),
  ('expression -> SIN LPAREN expression RPAREN','expression',4,'p_expression_sin','/home/kristoffer/PycharmProjects/test/calc.py',91),
  ('expression -> MINUS expression','expression',2,'p_expression_uminus','/home/kristoffer/PycharmProjects/test/calc.py',96),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','/home/kristoffer/PycharmProjects/test/calc.py',100),
  ('expression -> NUMBER','expression',1,'p_expression_number','/home/kristoffer/PycharmProjects/test/calc.py',104),
  ('expression -> PI','expression',1,'p_expression_pi','/home/kristoffer/PycharmProjects/test/calc.py',108),
  ('expression -> NAME','expression',1,'p_expression_name','/home/kristoffer/PycharmProjects/test/calc.py',112),
]
