
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = 'm\xb8!ZkE\x97\xfd=FK\x98?(J['
    
_lr_action_items = {'$end':([2,3,4,6,8,16,18,19,20,21,22,23,25,],[-11,-10,0,-2,-11,-8,-1,-9,-3,-6,-4,-5,-7,]),'FRAC':([0,1,5,7,10,12,13,14,15,17,],[1,1,1,1,1,1,1,1,1,1,]),'DIVIDE':([2,3,6,8,9,11,16,18,19,20,21,22,23,24,25,],[-11,-10,13,-11,13,13,-8,13,-9,13,-6,13,-5,13,-7,]),'RPAREN':([3,8,11,16,19,20,21,22,23,25,],[-10,-11,19,-8,-9,-3,-6,-4,-5,-7,]),'NUMBER':([0,1,5,7,10,12,13,14,15,17,],[3,3,3,3,3,3,3,3,3,3,]),'EQUALS':([2,],[10,]),'MIDDLE':([3,8,9,16,19,20,21,22,23,25,],[-10,-11,17,-8,-9,-3,-6,-4,-5,-7,]),'PLUS':([2,3,6,8,9,11,16,18,19,20,21,22,23,24,25,],[-11,-10,12,-11,12,12,-8,12,-9,-3,-6,-4,-5,12,-7,]),'LPAREN':([0,1,5,7,10,12,13,14,15,17,],[5,5,5,5,5,5,5,5,5,5,]),'END':([3,8,16,19,20,21,22,23,24,25,],[-10,-11,-8,-9,-3,-6,-4,-5,25,-7,]),'TIMES':([2,3,6,8,9,11,16,18,19,20,21,22,23,24,25,],[-11,-10,15,-11,15,15,-8,15,-9,15,-6,15,-5,15,-7,]),'MINUS':([0,1,2,3,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,],[7,7,-11,-10,7,14,7,-11,14,7,14,7,7,7,7,-8,7,14,-9,-3,-6,-4,-5,14,-7,]),'NAME':([0,1,5,7,10,12,13,14,15,17,],[2,8,8,8,8,8,8,8,8,8,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,1,5,7,10,12,13,14,15,17,],[6,9,11,16,18,20,21,22,23,24,]),'statement':([0,],[4,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> NAME EQUALS expression','statement',3,'p_statement_assign','/home/kristoffer/PycharmProjects/test/calc.py',66),
  ('statement -> expression','statement',1,'p_statement_expr','/home/kristoffer/PycharmProjects/test/calc.py',70),
  ('expression -> expression PLUS expression','expression',3,'p_expression_binop','/home/kristoffer/PycharmProjects/test/calc.py',74),
  ('expression -> expression MINUS expression','expression',3,'p_expression_binop','/home/kristoffer/PycharmProjects/test/calc.py',75),
  ('expression -> expression TIMES expression','expression',3,'p_expression_binop','/home/kristoffer/PycharmProjects/test/calc.py',76),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression_binop','/home/kristoffer/PycharmProjects/test/calc.py',77),
  ('expression -> FRAC expression MIDDLE expression END','expression',5,'p_expression_devide','/home/kristoffer/PycharmProjects/test/calc.py',84),
  ('expression -> MINUS expression','expression',2,'p_expression_uminus','/home/kristoffer/PycharmProjects/test/calc.py',89),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','/home/kristoffer/PycharmProjects/test/calc.py',93),
  ('expression -> NUMBER','expression',1,'p_expression_number','/home/kristoffer/PycharmProjects/test/calc.py',97),
  ('expression -> NAME','expression',1,'p_expression_name','/home/kristoffer/PycharmProjects/test/calc.py',101),
]
